#!/usr/bin/env bash
# Takes a subdomain and a domain and returns information about the subdomain

print_info () {
    local subdomain="$1"
    local domain="$2"
    local ip_address="$(dig +short "$subdomain.$domain")"
    
    if [ -n "$ip_address" ]; then
        echo "Your subdomain $subdomain points to IP: $ip_address"
    else
        echo "Failed to retrieve IP address for subdomain $subdomain"
    fi
}

if [ "$#" -eq 2 ]
then
    print_info "$2" "$1"
else
    print_info "www" "$1"
    print_info "lb-01" "$1"
    print_info "web-01" "$1"
    print_info "web-02" "$1"
fi

