#!/bin/env  bash

# Check if the script is being run as root
if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root or with sudo."
  exit 1
fi

# Update the package list to ensure we install the latest packages
apt update

# Install HAProxy
apt install -y haproxy

# Backup the default HAProxy configuration file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Create a new HAProxy configuration file
cat > /etc/haproxy/haproxy.cfg <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.224.63.115:80 check
    server web-02 54.162.42.29:80 check
EOL

# Enable and start HAProxy
systemctl enable haproxy
systemctl start haproxy

# Check HAProxy status
systemctl status haproxy

echo "HAProxy has been installed and configured."

