#!/bin/env bash

echo "Listening TCP Connections:"
ss -tlnp | awk 'NR>1 && /LISTEN/ {print $1, $5, $6}' | sed 's/.*pid=//' | awk '{print $1, $3}' | while read -r proto local_address state; do
    pid=$(echo "$state" | awk -F/ '{print $1}')
    program=$(echo "$state" | awk -F/ '{print $2}')
    echo "Protocol: $proto, Local Address: $local_address, PID: $pid, Program: $program"
done

echo "Listening UDP Connections:"
ss -ulnp | awk 'NR>1 && /UNCONN/ {print $1, $5}' | sed 's/.*pid=//' | awk '{print $1}' | while read -r proto local_address; do
    pid=$(ss -pulnp | awk -v addr="$local_address" '$0 ~ addr {print $6}' | awk -F/ '{print $1}')
    program=$(ss -pulnp | awk -v addr="$local_address" '$0 ~ addr {print $6}' | awk -F/ '{print $2}')
    echo "Protocol: $proto, Local Address: $local_address, PID: $pid, Program: $program"
done

echo "Listening UNIX Domain Sockets:"
ss -xlnp | awk 'NR>1 && /LISTEN/ {print $1, $5}' | sed 's/.*pid=//' | awk '{print $1}' | while read -r proto local_address; do

