#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

Hour=0

while [ $Hour -le 12 ]
do
  echo "Hour: $Hour"
  minutes=0
  while [ $minutes -le 59 ]
  do
    printf "%02d\n" $minutes
    (( minutes++ ))
  done
  (( Hour++ ))
done

