#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
# except for TCP ports 22, 443, and 80.

# Install UFW non-interactively
apt-get update
apt-get install -y ufw

# Enable IPV6 in UFW
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Disable and then enable UFW to reset the rules
ufw disable
ufw enable

# Set default policies
ufw default deny incoming
ufw default allow outgoing

# Allow specific ports
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

